- hosts: all
  become: true
  tasks:
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: "python3-pip"
    apt: pkg=python3-pip state=present

  - name: Install Docker Module for Python
    pip:
      name: docker
      
  - name: Ensure docker-compose is installed and available
    shell: curl -L https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    
  - name: Changing perm of "/usr/local/bin/docker-compose", adding "+x"
    file: dest=/usr/local/bin/docker-compose mode=a+x